config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :rooms

  root to: 'rooms#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :room

  validates :from, presence: true
  validates :content, presence: true
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :messages, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :new_room, only: %i[new create]
  before_action :find_room, only: %i[show edit update destroy]

  def index
    @rooms = Room.all
  end

  def show
    @messages = @room.messages.order(created_at: :desc).limit(10).to_a.reverse
  end

  def new; end

  def create
    if @room.update(params.require(:room).permit(:name))
      redirect_to @room
    else
      render :new
    end
  end

  def edit; end

  def update
    if @room.update(params.require(:room).permit(:name))
      redirect_to @room
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to root_path
  end

  private

  def new_room
    @room = Room.new
  end

  def find_room
    @room = Room.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('site.title') %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to root_path, class: 'navbar-brand mr-0' do %>
        <%= mdi_tag('forum') %>
      <% end %>

      <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to t('site.title'), root_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-md-4 offset-md-4 pt-4">
          <%= yield %>
        </div>
      </div>
    </div>

    <%= yield :bottom %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_for room do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name, autofocus: true, autocomplete: 'name', class: 'form-control' %>

  <%= f.submit t('submit'), class: 'btn btn-primary form-control mt-3 mb-2' %>
<% end %>

app/views/rooms/edit.html.erb
<h2><%= t('.header', room: @room.name) %></h2>
<%= render 'form', room: @room %>

app/views/rooms/index.html.erb
<h2><%= t('.welcome') %></h2>
<% if @rooms.present? %>
  <% @rooms.each do |room| %>
    <div><%= link_to room.name, room %></div>
  <% end %>
<% else %>
  <%= t('.no_rooms') %>
<% end %>
<div class="pt-3">
  <%= link_to t('.new_room'), new_room_path, class: 'btn btn-sm btn-primary' %>
</div>

app/views/rooms/new.html.erb
<h2><%= t('.header') %></h2>
<%= render 'form', room: @room %>

app/views/rooms/show.html.erb
<% content_for :bottom do %>
  <div id="get-name-modal" class="modal" role="dialog" data-keyboard="false">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"><%= t('.modal.title', room: @room.name) %></h5>
        </div>
        <div class="modal-body">
          <div id="no-name-error" class="alert alert-danger" style="display: none;">
            <%= t('.modal.error') %>
          </div>
          <p><%= t('.modal.body') %></p>
          <input type="text" class="form-control" autofocus="autofocus">
        </div>
        <div class="modal-footer">
          <button id="save-name-button" type="button" class="btn btn-primary"><%= t('.modal.go') %></button>
        </div>
      </div>
    </div>
  </div>
<% end %>

<h2 class="text-center"><%= @room.name %></h2>
<div class="text-center pb-4">
  <%= link_to t('.edit'), edit_room_path(@room), class: 'btn btn-sm btn-primary' %>
  <%= link_to t('.destroy'), room_path(@room), method: :delete, class: 'btn btn-sm btn-danger' %>
</div>
<table id="conversation" class="table table-striped" data-room="<%= @room.id %>">
  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td class="message-from"><%= message.from %></td>
        <td class="message-content"><%= message.content %></td>
      </tr>
    <% end %>
    <% if @messages.blank? %>
      <tr id="no-messages">
        <td colspan="2" class="text-small text-muted"><%= t('.no_messages') %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div id="content-fields" class="pt-2">
  <div id="no-message-error" class="alert alert-danger" style="display: none;">
    <%= t('.form.error') %>
  </div>
  <textarea class="form-control" placeholder="<%= t('.form.placeholder') %>"></textarea>
  <div class="mt-2 text-right">
    <button id="content-button" type="button" class="btn btn-primary">
      <%= t('.form.submit') %>
    </button>
  </div>
</div>